baseURL = "https://arashtaher.com"
languageCode = "en-us"
title = "Arash Taher"
author = "Arash Taher"
enableRobotsTXT = true

# Enable taxonomies for tags
[taxonomies]
  tag = "tags"
[permalinks]
  blog = "/blog/:slug/"
  tags = "/tags/:slug"

[params]
  description = "Arash Taher personal website"

  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  # images = ["images/share.png"]

  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Arash Taher"

# Disable Hugo's built-in syntax highlighting - using Highlight.js instead
[markup]
  [markup.highlight]
    codeFences = false